#g++ -std=c++11 -g -shared -fPIC  -I/home/liqian/inferences/InferLib  -I/home/ddk/ddk//include/inc  -I/home/ddk/ddk//include/third_party/protobuf/include  -I/home/ddk/ddk//include/third_party/cereal/include  -I/home/ddk/ddk//include/libc_sec/include  -I/home/ddk/ddk//include/third_party/opencv/include  -I/home/ddk/ddk//include/third_party/gflags/include  -I/home/liqian/inferences/InferLib/common -L/home/ddk/ddk//uihost/lib/  -L/home/ddk/ddk//  -Lout/  -lmatrix   /home/liqian/inferences/InferLib/main.cpp -o /home/liqian/inferences/InferLib/infer.so

#@g++ -std=c++11 -g -shared -fPIC  -I/home/liqian/inferences/InferLib  -I/home/ddk/ddk//include/inc  -I/home/ddk/ddk//include/third_party/protobuf/include  -I/home/ddk/ddk//include/third_party/cereal/include  -I/home/ddk/ddk//include/libc_sec/include  -I/home/ddk/ddk//include/third_party/opencv/include  -I/home/ddk/ddk//include/third_party/gflags/include  -I/home/liqian/inferences/InferLib/common -c /home/liqian/inferences/InferLib/main.cpp -o /home/liqian/inferences/InferLib/out/main.o
#@g++ -std=c++11 -g -shared -fPIC -o /home/liqian/inferences/InferLib/out/infer.so  /home/liqian/inferences/InferLib/out/main.o -Wl,--whole-archive  -Wl,--no-whole-archive -Wl,--start-group  -Wl,--end-group  -L/home/ddk/ddk//uihost/lib/  -L/home/ddk/ddk//  -Lout/  -lmatrix  -ldrvdevdrv  -ldrvhdc_host  -lmmpa  -lcrypto  -lc_sec  -lpthread  -lprotobuf  -lprofilerclient  -lslog  -lcnpy  -ldl  -lgflags  -lopencv_world



#g++ -std=c++11 -g -shared -fPIC  -I/home/liqian/inferences/InferLib  -I/home/ddk/ddk//include/inc  -I/home/ddk/ddk//include/third_party/protobuf/include  -I/home/ddk/ddk//include/third_party/cereal/include  -I/home/ddk/ddk//include/libc_sec/include  -I/home/ddk/ddk//include/third_party/opencv/include  -I/home/ddk/ddk//include/third_party/gflags/include  -I/home/liqian/inferences/InferLib/common -L/home/ddk/ddk//uihost/lib/  -L/home/ddk/ddk//  -Lout/  -lmatrix   /home/liqian/inferences/InferLib/main.cpp -o /home/liqian/inferences/InferLib/infer.so



g++ -std=c++11 -g -shared -fPIC  -I/home/liqian/inferences/InferLib  -I/home/ddk/ddk//include/inc  -I/home/ddk/ddk//include/third_party/protobuf/include  -I/home/ddk/ddk//include/third_party/cereal/include  -I/home/ddk/ddk//include/libc_sec/include  -I/home/ddk/ddk//include/third_party/opencv/include  -I/home/ddk/ddk//include/third_party/gflags/include  -I/home/liqian/inferences/InferLib/common -L/home/ddk/ddk//uihost/lib/  -L/home/ddk/ddk//  -Lout/  -lmatrix   /home/liqian/inferences/InferLib/demo.cpp -o /home/liqian/inferences/InferLib/infer.so
