#python bioavailability_predict.py 'C1=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=C1'
# CUDA_VISIBLE_DEVICES=5 python3 bioavailability_predict.py 'COc1nc(C)nc(Cl)c1NC1=NCCN1'
python3 bioavailability_predict.py 'COc1nc(C)nc(Cl)c1NC1=NCCN1'
#python bioavailability_predict.py 'C1=CC=CC=C1'
#python bioavailability_predict.py 'CCC(=O)O'
